# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1,2,3],[4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('int32'), 6, numpy.ndarray)

In [5]:
# Attributes of 3-dimensional array
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 3, 3), 3, dtype('int32'), 18, numpy.ndarray)

In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(a2, columns=["First", "Second", "Third"])
df

First  Second  Third
0      1       2      3
1      4       5      6

In [7]:
# Create an array of shape (10, 2) with only ones
ones = np.ones(shape=(10,2))
ones.shape

(10, 2)

In [8]:
# Create an array of shape (7, 2, 3) of only zeros
zeroes = np.zeros(shape=(7,2,3))
zeroes.shape

(7, 2, 3)

In [9]:
# Create an array within a range of 0 and 100 with step 3
li = np.arange(0,100,3)
type(li)

numpy.ndarray

In [10]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_1 = np.random.randint(0, 10, (7,2))
random_1

array([[5, 7],
       [2, 5],
       [2, 3],
       [1, 2],
       [0, 8],
       [2, 7],
       [3, 8]])

In [11]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_2 = np.random.rand(3,5)
print(random_2.shape)
random_2

(3, 5)


array([[0.21391233, 0.4322758 , 0.80196671, 0.38963436, 0.56058062],
       [0.13838359, 0.66690814, 0.53484558, 0.81639166, 0.05760693],
       [0.65902167, 0.32505988, 0.63510235, 0.19806709, 0.39938678]])

In [12]:
# Set the random seed to 42
np.random.seed(42)
# Create a random array of numbers between 0 & 10 of size (4, 6)
random_3 = np.random.rand(4,6)
random_3

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
        0.15599452],
       [0.05808361, 0.86617615, 0.60111501, 0.70807258, 0.02058449,
        0.96990985],
       [0.83244264, 0.21233911, 0.18182497, 0.18340451, 0.30424224,
        0.52475643],
       [0.43194502, 0.29122914, 0.61185289, 0.13949386, 0.29214465,
        0.36636184]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [13]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_4 = np.random.randint(0, 10, size=(3,7))
# Find the unique numbers in the array you just created
print(random_4)
np.unique(random_4)


[[2 6 3 8 2 4 2]
 [6 4 8 6 1 3 8]
 [1 9 8 9 4 1 3]]


array([1, 2, 3, 4, 6, 8, 9])

In [14]:
# Find the 0'th index of the latest array you created
random_4[0]

array([2, 6, 3, 8, 2, 4, 2])

In [15]:
# Get the first 2 rows of latest array you created
random_4[:2]

array([[2, 6, 3, 8, 2, 4, 2],
       [6, 4, 8, 6, 1, 3, 8]])

In [54]:
# Get the first 2 values of the first 2 rows of the latest array
random_4[:2,:2]


array([[2, 6],
       [6, 4]])

In [57]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
li1 = np.random.randint(0, 10,(3,5))
li2 = np.ones(shape=(3,5))


In [59]:
li1

array([[9, 1, 9, 3, 7],
       [6, 8, 7, 4, 1],
       [4, 7, 9, 8, 8]])

In [60]:
li2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [58]:
# Add the two arrays together
li1 + li2

array([[10.,  2., 10.,  4.,  8.],
       [ 7.,  9.,  8.,  5.,  2.],
       [ 5.,  8., 10.,  9.,  9.]])

In [62]:
# Create another array of ones of shape (5, 3)
li3 = np.ones(shape=(5,3))
li3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [64]:
# Try add the array of ones and the other most recent array together
# li1 + li3 

# The above line  of code will error out since the shapes are not the same

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [65]:
# Create another array of ones of shape (3, 5)
li2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [70]:
# Subtract the new array of ones from the other most recent array
np.subtract(li1,li2)

array([[8., 0., 8., 2., 6.],
       [5., 7., 6., 3., 0.],
       [3., 6., 8., 7., 7.]])

In [69]:
# Multiply the ones array with the latest array
np.multiply(li1, li2)

array([[9., 1., 9., 3., 7.],
       [6., 8., 7., 4., 1.],
       [4., 7., 9., 8., 8.]])

In [71]:
# Take the latest array to the power of 2 using '**'
li1 ** 2

array([[81,  1, 81,  9, 49],
       [36, 64, 49, 16,  1],
       [16, 49, 81, 64, 64]])

In [72]:
# Do the same thing with np.square()
np.square(li1)

array([[81,  1, 81,  9, 49],
       [36, 64, 49, 16,  1],
       [16, 49, 81, 64, 64]])

In [73]:
# Find the mean of the latest array using np.mean()
np.mean(li1)

6.066666666666666

In [74]:
# Find the maximum of the latest array using np.max()
np.max(li1)

9

In [75]:
# Find the minimum of the latest array using np.min()
np.min(li1)

1

In [76]:
# Find the standard deviation of the latest array
np.std(li1)

2.6948510575210314

In [78]:
# Find the variance of the latest array
np.var(li1)

7.262222222222222

In [81]:
# Reshape the latest array to (3, 5, 1)
li1.reshape((3,5,1))

array([[[9],
        [1],
        [9],
        [3],
        [7]],

       [[6],
        [8],
        [7],
        [4],
        [1]],

       [[4],
        [7],
        [9],
        [8],
        [8]]])

In [82]:
# Transpose the latest array
li1.T

array([[[9, 6, 4],
        [1, 8, 7],
        [9, 7, 9],
        [3, 4, 8],
        [7, 1, 8]]])

What does the transpose do?

In [84]:
# Create two arrays of random integers between 0 to 10
arr = np.random.randint(0,10, size=(3,3))
# one of size (3, 3) the other of size (3, 2)
arr1 = np.random.randint(0,10, size=(3,2))

In [85]:
# Perform a dot product on the two newest arrays you created
arr.dot(arr1)

array([[ 58,  49],
       [ 20,  12],
       [129,  96]])

In [86]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
arr2 = np.random.randint(0,10, size=(4,3))
arr3 = np.random.randint(0,10, size=(4,3))

In [88]:
# Perform a dot product on the two newest arrays you created
# arr2.dot(arr3)

# It will raise an error since the shape of the two arrays doesnt foloow the dimension order m * n & n * p where m,n and p are integers

It doesn't work. How would you fix it?

In [89]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both

arr2.dot(arr3.T)

array([[ 87, 128, 122,  57],
       [ 71,  92,  68,  45],
       [  8,  42,  63,  30],
       [ 34,  52,  58,  18]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [90]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
p = np.random.randint(0,10,size=(3,4))
p1 = np.random.randint(0,10,size=(3,4))

In [91]:
p1

array([[5, 3, 9, 6],
       [8, 6, 0, 0],
       [8, 8, 3, 8]])

In [92]:
p

array([[3, 4, 6, 6],
       [3, 6, 2, 5],
       [1, 9, 8, 4]])

In [93]:
# Compare the two arrays with '>'
p > p1

array([[False,  True, False, False],
       [False, False,  True,  True],
       [False,  True,  True, False]])

What happens when you compare the arrays with `>`?

In [94]:
# Compare the two arrays with '>='
p >= p1

array([[False,  True, False,  True],
       [False,  True,  True,  True],
       [False,  True,  True, False]])

In [95]:
# Find which elements of the first array are greater than 7
p > 7

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True, False]])

In [96]:
# Which parts of each array are equal? (try using '==')
p == p1

array([[False, False, False,  True],
       [False,  True, False, False],
       [False, False, False, False]])

In [98]:
p

array([[3, 4, 6, 6],
       [3, 6, 2, 5],
       [1, 9, 8, 4]])

In [97]:
# Sort one of the arrays you just created in ascending order
np.sort(p)

array([[3, 4, 6, 6],
       [2, 3, 5, 6],
       [1, 4, 8, 9]])

In [99]:
# Sort the indexes of one of the arrays you just created
np.argsort(p)

array([[0, 1, 2, 3],
       [2, 0, 3, 1],
       [0, 3, 2, 1]], dtype=int64)

In [105]:
# Find the index with the maximum value in one of the arrays you've created
print(np.argmax(p))


9


In [106]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(p)

8

In [107]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
print(np.argmax(p, axis = 1))


[2 1 1]


In [108]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
print(np.argmin(p, axis = 0))


[2 0 1 2]


In [112]:
# Create an array of normally distributed random numbers
li4 = np.random.normal(size=(4,4))
li4

array([[-1.30995069,  2.94366342, -1.0962658 ,  0.91488432],
       [-0.66606062, -0.51378749,  0.3013228 , -1.45851692],
       [-0.66273831, -0.14647281, -0.84601702, -0.82248937],
       [ 1.08672702,  1.00498688, -0.44176602, -0.08416509]])

In [116]:
# Create an array with 10 evenly spaced numbers between 1 and 100
arra = np.arange(0,100,10)
arra

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.