In [23]:
import numpy as np

DataTypes & Attributes


In [24]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [25]:
type(a1)

numpy.ndarray

In [26]:
a2 = np.array([[1,2,3.3],
              [4,5,6.5]])

a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
                [[10,11,12],
                [13,14,15],
                [16,17,18]]])

In [27]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [28]:
a2.shape

(2, 3)

In [29]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [30]:
a1.shape

(3,)

In [31]:
a2.shape

(2, 3)

In [32]:
a3.shape

(2, 3, 3)

In [33]:
a1.ndim, a2.ndim , a3.ndim

(1, 2, 3)

In [34]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [35]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [36]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [37]:
#Create a datafram from numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

Creating NUmpy Arrays

In [38]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [39]:
sample_array.dtype

dtype('int32')

In [43]:
ones = np.ones(shape=[2,3], dtype=int)
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [44]:
ones.dtype

dtype('int32')

In [46]:
type(ones)

numpy.ndarray

In [48]:
zeroes = np.zeros(shape=[2,3])
zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

In [50]:
range_Array = np.arange(0, 10, 2)
range_Array

array([0, 2, 4, 6, 8])

In [55]:
random_array = np.random.randint(0,10, size=(3,5))
random_array

array([[1, 4, 2, 6, 2],
       [1, 3, 3, 4, 3],
       [3, 8, 9, 9, 4]])

In [56]:
random_array.size

15

In [57]:
random_array.shape

(3, 5)

In [59]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.38469296, 0.74410597, 0.01428104],
       [0.80490478, 0.46309374, 0.36216432],
       [0.60556501, 0.44484228, 0.38341252],
       [0.25279249, 0.31236292, 0.51349716],
       [0.26390616, 0.49868353, 0.1158865 ]])

In [60]:
random_array_2.shape

(5, 3)

In [62]:
random_array_3 = np.random.rand(5,3)
random_array_3

# It is to be noted that the rndom arrays which we are generating are not random in nature, they are said to be pseudo random in nature

array([[0.49532575, 0.5856058 , 0.29204651],
       [0.02011323, 0.19486481, 0.04728042],
       [0.05305974, 0.13336268, 0.84397546],
       [0.5112814 , 0.05847355, 0.29556434],
       [0.9009667 , 0.36663511, 0.39813687]])

In [ ]:
#Pseudo Random numbers
np.random.seed()