In [1]:
import numpy as np

DataTypes & Attributes


In [2]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2,3.3],
              [4,5,6.5]])

a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
                [[10,11,12],
                [13,14,15],
                [16,17,18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a2.shape

(2, 3)

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
a1.ndim, a2.ndim , a3.ndim

(1, 2, 3)

In [12]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [13]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [14]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [15]:
#Create a datafram from numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

Creating NUmpy Arrays

In [16]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [17]:
sample_array.dtype

dtype('int32')

In [18]:
ones = np.ones(shape=[2,3], dtype=int)
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [19]:
ones.dtype

dtype('int32')

In [20]:
type(ones)

numpy.ndarray

In [21]:
zeroes = np.zeros(shape=[2,3])
zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
range_Array = np.arange(0, 10, 2)
range_Array

array([0, 2, 4, 6, 8])

In [23]:
random_array = np.random.randint(0,10, size=(3,5))
random_array

array([[8, 0, 6, 6, 0],
       [6, 4, 4, 1, 4],
       [1, 0, 9, 6, 4]])

In [24]:
random_array.size

15

In [25]:
random_array.shape

(3, 5)

In [26]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.98846304, 0.40682095, 0.59171258],
       [0.62464256, 0.65810036, 0.00101354],
       [0.69506962, 0.40797889, 0.68878306],
       [0.37323782, 0.95529019, 0.8698945 ],
       [0.70500582, 0.43870666, 0.75042422]])

In [27]:
random_array_2.shape

(5, 3)

In [28]:
random_array_3 = np.random.rand(5,3)
random_array_3

# It is to be noted that the rndom arrays which we are generating are not random in nature, they are said to be pseudo random in nature

array([[0.77797542, 0.18655296, 0.88365518],
       [0.60665304, 0.93037446, 0.75541387],
       [0.86023701, 0.67051351, 0.59593765],
       [0.94896463, 0.36218258, 0.15311441],
       [0.27947346, 0.16703927, 0.87022662]])

In [29]:
#Pseudo Random numbers
np.random.seed()